<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Real-Time-Audio-Intercommunicator-(RTAI)" data-toc-modified-id="Real-Time-Audio-Intercommunicator-(RTAI)-1"><span class="toc-item-num">1&nbsp;&nbsp;</span><a>Real Time Audio Intercommunicator (RTAI)</a></a></span><ul class="toc-item"><li><span><a href="#The-sounddevice.Stream-class" data-toc-modified-id="The-sounddevice.Stream-class-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>The <a href="https://python-sounddevice.readthedocs.io/en/0.3.15/api/streams.html" target="_blank"><code>sounddevice.Stream</code></a> class</a></span></li><li><span><a href="#Transmitting-live-data-through-the-Internet" data-toc-modified-id="Transmitting-live-data-through-the-Internet-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Transmitting live data through the Internet</a></span></li><li><span><a href="#Some-socket-stuff-in-Python" data-toc-modified-id="Some-socket-stuff-in-Python-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Some <a href="https://docs.python.org/3/library/socket.html" target="_blank"><code>socket</code></a> stuff in Python</a></span><ul class="toc-item"><li><span><a href="#Array-declarations" data-toc-modified-id="Array-declarations-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Array declarations</a></span></li><li><span><a href="#NumPy's-types" data-toc-modified-id="NumPy's-types-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>NumPy's types</a></span></li></ul></li></ul></li></ul></div>

## And some [NumPy](https://numpy.org) stuff
Numpy extends lists in Python when we need to work with arrays of numbers, providing a higher performance (throught [vectorization](https://en.wikipedia.org/wiki/Array_programming)) and [functionality](https://numpy.org/doc/stable/reference/index.html).

In [2]:
try:
    import numpy as np
except ModuleNotFoundError:
    import os
    os.system("pip3 install numpy --user")
    import numpy as np

### Array declarations

In [5]:
l = [1, 2]
l

[1, 2]

In [6]:
type(l)

list

In [4]:
A = np.array(l) # Use "array", not "ndarray"
A

array([1, 2])

In [7]:
type(A)

numpy.ndarray

In [9]:
A[0]

1

In [12]:
Z = np.zeros((3,2,4))
Z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### NumPy's data [types](https://numpy.org/devdocs/user/basics.types.html)

In [8]:
type(A[0])

numpy.int64

In [10]:
A = np.array(l, dtype=np.float32)
A

array([1., 2.], dtype=float32)

In [11]:
type(A[0])

numpy.float32

In [13]:
Z = np.zeros((3,2,4), dtype=np.uint8)
Z

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=uint8)

In [14]:
type(Z[1,1,1])

numpy.uint8

### Slicing

In [15]:
A = np.arange(10)**3
A

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [16]:
A[2] # Indexing

8

In [17]:
A[2:4] # Indexing using slicing

array([ 8, 27])

In [18]:
A[2:] # Slicing

array([  8,  27,  64, 125, 216, 343, 512, 729])